### ISSUE TITLE
Before release 1.2.0 checklist

### ISSUE THREAD

**Issue by AleksandarDev** [Sparkiy/sparkiy-client#56]
- [x] Set next release timer
- [x] Set new version on home page
- [x] Build packages
- [x] Change description (what's new notes)
